//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutButtonContent {
            get {
                return ResourceManager.GetString("AboutButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project page on GitHub.
        /// </summary>
        public static string AboutButtonTooltip {
            get {
                return ResourceManager.GetString("AboutButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run application as an administrator so that the library can get complete information about the current state of the computer hardware.
        ///
        ///Press OK to restart the application as administrator..
        /// </summary>
        public static string AdminPrivilegesRequirementMessageText {
            get {
                return ResourceManager.GetString("AdminPrivilegesRequirementMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less information about PC.
        /// </summary>
        public static string AdminPrivilegesRequirementMessageTitle {
            get {
                return ResourceManager.GetString("AdminPrivilegesRequirementMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodetect Hardware:.
        /// </summary>
        public static string AutoDetectHardwareSwitchText {
            get {
                return ResourceManager.GetString("AutoDetectHardwareSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/Off autodetect hardware.
        /// </summary>
        public static string AutoDetectHardwareTooltip {
            get {
                return ResourceManager.GetString("AutoDetectHardwareTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string AutoStartupSwitchText {
            get {
                return ResourceManager.GetString("AutoStartupSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch HSMonitor at Windows startup.
        /// </summary>
        public static string AutoStartupTooltip {
            get {
                return ResourceManager.GetString("AutoStartupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable auto update.
        /// </summary>
        public static string AutoUpdateSwitchText {
            get {
                return ResourceManager.GetString("AutoUpdateSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/Off auto update.
        /// </summary>
        public static string AutoUpdateTooltip {
            get {
                return ResourceManager.GetString("AutoUpdateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward compability.
        /// </summary>
        public static string BackwardCompabilityText {
            get {
                return ResourceManager.GetString("BackwardCompabilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable backward compatibility for devices with software version 1.1.4 and below.
        /// </summary>
        public static string BackwardCompabilityTooltip {
            get {
                return ResourceManager.GetString("BackwardCompabilityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate:.
        /// </summary>
        public static string BaudRateText {
            get {
                return ResourceManager.GetString("BaudRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonTooltip {
            get {
                return ResourceManager.GetString("CancelButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckForUpdatesTooltip {
            get {
                return ResourceManager.GetString("CheckForUpdatesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseAppFromTrayButtonText {
            get {
                return ResourceManager.GetString("CloseAppFromTrayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close HSMonitor.
        /// </summary>
        public static string CloseButtonTooltip {
            get {
                return ResourceManager.GetString("CloseButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application configuration file was not found in the program folder or was modified manually.
        ///Please reinstall the program to fix the problem..
        /// </summary>
        public static string ConfigurationFileErrorMessageText {
            get {
                return ResourceManager.GetString("ConfigurationFileErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU icon:.
        /// </summary>
        public static string CustomCPUIconText {
            get {
                return ResourceManager.GetString("CustomCPUIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom CPU name:.
        /// </summary>
        public static string CustomCPUNameText {
            get {
                return ResourceManager.GetString("CustomCPUNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU icon:.
        /// </summary>
        public static string CustomGPUIconText {
            get {
                return ResourceManager.GetString("CustomGPUIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom GPU name:.
        /// </summary>
        public static string CustomGPUNameText {
            get {
                return ResourceManager.GetString("CustomGPUNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM icon:.
        /// </summary>
        public static string CustomRAMIconText {
            get {
                return ResourceManager.GetString("CustomRAMIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default CPU Frequency(MHz):.
        /// </summary>
        public static string DefaultCPUFreqText {
            get {
                return ResourceManager.GetString("DefaultCPUFreqText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default GPU Frequency(MHz):.
        /// </summary>
        public static string DefaultGPUFreqText {
            get {
                return ResourceManager.GetString("DefaultGPUFreqText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display brightness:.
        /// </summary>
        public static string DisplayBrightnessText {
            get {
                return ResourceManager.GetString("DisplayBrightnessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string DownloadingText {
            get {
                return ResourceManager.GetString("DownloadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        public static string Hardware {
            get {
                return ResourceManager.GetString("Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch HSMonitor hidden at Windows startup.
        /// </summary>
        public static string HiddenAutoStartupTooltip {
            get {
                return ResourceManager.GetString("HiddenAutoStartupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start hidden.
        /// </summary>
        public static string HiddenStartSwitchText {
            get {
                return ResourceManager.GetString("HiddenStartSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide HSMonitor.
        /// </summary>
        public static string HideButtonTooltip {
            get {
                return ResourceManager.GetString("HideButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MessageBoxCancelButtonText {
            get {
                return ResourceManager.GetString("MessageBoxCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, the error text is shown below:.
        /// </summary>
        public static string MessageBoxErrorText {
            get {
                return ResourceManager.GetString("MessageBoxErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error has occurred.
        /// </summary>
        public static string MessageBoxErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MessageBoxOkButtonText {
            get {
                return ResourceManager.GetString("MessageBoxOkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string MessageBoxRestartButtonText {
            get {
                return ResourceManager.GetString("MessageBoxRestartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using version.
        /// </summary>
        public static string NewUpdateMessageCurrentVersionText {
            get {
                return ResourceManager.GetString("NewUpdateMessageCurrentVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available!.
        /// </summary>
        public static string NewUpdateMessageTitle {
            get {
                return ResourceManager.GetString("NewUpdateMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the application now?.
        /// </summary>
        public static string NewUpdateMessageUpdateText {
            get {
                return ResourceManager.GetString("NewUpdateMessageUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is new version available:.
        /// </summary>
        public static string NewUpdateMessageVersionText {
            get {
                return ResourceManager.GetString("NewUpdateMessageVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is busy!.
        /// </summary>
        public static string NoConnectionBusyMessageText {
            get {
                return ResourceManager.GetString("NoConnectionBusyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect a device or choose a different port..
        /// </summary>
        public static string NoConnectionErrorMessageText {
            get {
                return ResourceManager.GetString("NoConnectionErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection!.
        /// </summary>
        public static string NoConnectionText {
            get {
                return ResourceManager.GetString("NoConnectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string OpenSettingsTooltip {
            get {
                return ResourceManager.GetString("OpenSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PawnIO allows you to get CPU information.
        /// </summary>
        public static string PawnIoInfo {
            get {
                return ResourceManager.GetString("PawnIoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PawnIO is not installed, do you want to install it?.
        /// </summary>
        public static string PawnIoNotInstalled {
            get {
                return ResourceManager.GetString("PawnIoNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PawnIO is outdated, do you want to update it?.
        /// </summary>
        public static string PawnIoOutdated {
            get {
                return ResourceManager.GetString("PawnIoOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project URL on GitHub:.
        /// </summary>
        public static string ProjectURLText {
            get {
                return ResourceManager.GetString("ProjectURLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all available ports.
        /// </summary>
        public static string RefreshPortsButtonTooltip {
            get {
                return ResourceManager.GetString("RefreshPortsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings to their defaults.
        /// </summary>
        public static string ResetButtonTooltip {
            get {
                return ResourceManager.GetString("ResetButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart the program to change the language..
        /// </summary>
        public static string RestartRequirementMessageText {
            get {
                return ResourceManager.GetString("RestartRequirementMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        public static string RestartRequirementMessageTitle {
            get {
                return ResourceManager.GetString("RestartRequirementMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator.
        /// </summary>
        public static string RunAsAdminSwitchText {
            get {
                return ResourceManager.GetString("RunAsAdminSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch HSMonitor as administrator directly.
        /// </summary>
        public static string RunAsAdminTooltip {
            get {
                return ResourceManager.GetString("RunAsAdminTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string SaveButtonTooltip {
            get {
                return ResourceManager.GetString("SaveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CPU:.
        /// </summary>
        public static string SelectCPUText {
            get {
                return ResourceManager.GetString("SelectCPUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select GPU:.
        /// </summary>
        public static string SelectGPUText {
            get {
                return ResourceManager.GetString("SelectGPUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        public static string SelectLanguageText {
            get {
                return ResourceManager.GetString("SelectLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial port:.
        /// </summary>
        public static string SerialPortText {
            get {
                return ResourceManager.GetString("SerialPortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButtonContent {
            get {
                return ResourceManager.GetString("SettingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string ShowWindowFromTrayButtonText {
            get {
                return ResourceManager.GetString("ShowWindowFromTrayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX Interval(ms):.
        /// </summary>
        public static string TXIntervalText {
            get {
                return ResourceManager.GetString("TXIntervalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available!.
        /// </summary>
        public static string UpdateAvailableText {
            get {
                return ResourceManager.GetString("UpdateAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update has been downloaded, you need to restart the program to install it..
        /// </summary>
        public static string UpdateCompletedText {
            get {
                return ResourceManager.GetString("UpdateCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart needed.
        /// </summary>
        public static string UpdateCompletedTitle {
            get {
                return ResourceManager.GetString("UpdateCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Download Progress.
        /// </summary>
        public static string UpdateDownloadProgressTooltip {
            get {
                return ResourceManager.GetString("UpdateDownloadProgressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re up to date.
        /// </summary>
        public static string UpToDateText {
            get {
                return ResourceManager.GetString("UpToDateText", resourceCulture);
            }
        }
    }
}
