//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutButtonContent {
            get {
                return ResourceManager.GetString("AboutButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project page on GitHub.
        /// </summary>
        public static string AboutButtonTooltip {
            get {
                return ResourceManager.GetString("AboutButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodetect Hardware:.
        /// </summary>
        public static string AutoDetectHardwareSwitchText {
            get {
                return ResourceManager.GetString("AutoDetectHardwareSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/Off autodetect hardware.
        /// </summary>
        public static string AutoDetectHardwareTooltip {
            get {
                return ResourceManager.GetString("AutoDetectHardwareTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string AutoStartupSwitchText {
            get {
                return ResourceManager.GetString("AutoStartupSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch HSMonitor at Windows startup.
        /// </summary>
        public static string AutoStartupTooltip {
            get {
                return ResourceManager.GetString("AutoStartupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable auto update.
        /// </summary>
        public static string AutoUpdateSwitchText {
            get {
                return ResourceManager.GetString("AutoUpdateSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/Off auto update.
        /// </summary>
        public static string AutoUpdateTooltip {
            get {
                return ResourceManager.GetString("AutoUpdateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate:.
        /// </summary>
        public static string BaudRateText {
            get {
                return ResourceManager.GetString("BaudRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonTooltip {
            get {
                return ResourceManager.GetString("CancelButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckForUpdatesTooltip {
            get {
                return ResourceManager.GetString("CheckForUpdatesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application.
        /// </summary>
        public static string CloseAppFromTrayButtonText {
            get {
                return ResourceManager.GetString("CloseAppFromTrayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close HSMonitor.
        /// </summary>
        public static string CloseButtonTooltip {
            get {
                return ResourceManager.GetString("CloseButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU icon:.
        /// </summary>
        public static string CustomCPUIconText {
            get {
                return ResourceManager.GetString("CustomCPUIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom CPU name:.
        /// </summary>
        public static string CustomCPUNameText {
            get {
                return ResourceManager.GetString("CustomCPUNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU icon:.
        /// </summary>
        public static string CustomGPUIconText {
            get {
                return ResourceManager.GetString("CustomGPUIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom GPU name:.
        /// </summary>
        public static string CustomGPUNameText {
            get {
                return ResourceManager.GetString("CustomGPUNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM icon:.
        /// </summary>
        public static string CustomRAMIconText {
            get {
                return ResourceManager.GetString("CustomRAMIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default CPU Frequency(MHz):.
        /// </summary>
        public static string DefaultCPUFreqText {
            get {
                return ResourceManager.GetString("DefaultCPUFreqText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default GPU Frequency(MHz):.
        /// </summary>
        public static string DefaultGPUFreqText {
            get {
                return ResourceManager.GetString("DefaultGPUFreqText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display brightness:.
        /// </summary>
        public static string DisplayBrightnessText {
            get {
                return ResourceManager.GetString("DisplayBrightnessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch HSMonitor hidden at Windows startup.
        /// </summary>
        public static string HiddenAutoStartupTooltip {
            get {
                return ResourceManager.GetString("HiddenAutoStartupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start hidden.
        /// </summary>
        public static string HiddenStartSwitchText {
            get {
                return ResourceManager.GetString("HiddenStartSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string OpenSettingsTooltip {
            get {
                return ResourceManager.GetString("OpenSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project URL on GitHub:.
        /// </summary>
        public static string ProjectURLText {
            get {
                return ResourceManager.GetString("ProjectURLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings to their defaults.
        /// </summary>
        public static string ResetButtonTooltip {
            get {
                return ResourceManager.GetString("ResetButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator.
        /// </summary>
        public static string RunAsAdminSwitchText {
            get {
                return ResourceManager.GetString("RunAsAdminSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch HSMonitor as administrator directly.
        /// </summary>
        public static string RunAsAdminTooltip {
            get {
                return ResourceManager.GetString("RunAsAdminTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string SaveButtonTooltip {
            get {
                return ResourceManager.GetString("SaveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CPU:.
        /// </summary>
        public static string SelectCPUText {
            get {
                return ResourceManager.GetString("SelectCPUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select GPU:.
        /// </summary>
        public static string SelectGPUText {
            get {
                return ResourceManager.GetString("SelectGPUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        public static string SelectLanguageText {
            get {
                return ResourceManager.GetString("SelectLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial port:.
        /// </summary>
        public static string SerialPortText {
            get {
                return ResourceManager.GetString("SerialPortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButtonContent {
            get {
                return ResourceManager.GetString("SettingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window.
        /// </summary>
        public static string ShowWindowFromTrayButtonText {
            get {
                return ResourceManager.GetString("ShowWindowFromTrayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX Interval(ms):.
        /// </summary>
        public static string TXIntervalText {
            get {
                return ResourceManager.GetString("TXIntervalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Download Progress.
        /// </summary>
        public static string UpdateDownloadProgressTooltip {
            get {
                return ResourceManager.GetString("UpdateDownloadProgressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Privileges Requirement Message Text.
        /// </summary>
        public static string AdminPrivilegesRequirementMessageText {
            get {
                return ResourceManager.GetString("AdminPrivilegesRequirementMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Privileges Requirement Message Title.
        /// </summary>
        public static string AdminPrivilegesRequirementMessageTitle {
            get {
                return ResourceManager.GetString("AdminPrivilegesRequirementMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box Ok Button Text.
        /// </summary>
        public static string MessageBoxOkButtonText {
            get {
                return ResourceManager.GetString("MessageBoxOkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box Cancel Button Text.
        /// </summary>
        public static string MessageBoxCancelButtonText {
            get {
                return ResourceManager.GetString("MessageBoxCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box Error Title.
        /// </summary>
        public static string MessageBoxErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connection Error Message Text.
        /// </summary>
        public static string NoConnectionErrorMessageText {
            get {
                return ResourceManager.GetString("NoConnectionErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connection Busy Message Text.
        /// </summary>
        public static string NoConnectionBusyMessageText {
            get {
                return ResourceManager.GetString("NoConnectionBusyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box Error Text.
        /// </summary>
        public static string MessageBoxErrorText {
            get {
                return ResourceManager.GetString("MessageBoxErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration File Error Message Text.
        /// </summary>
        public static string ConfigurationFileErrorMessageText {
            get {
                return ResourceManager.GetString("ConfigurationFileErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Update Message Title.
        /// </summary>
        public static string NewUpdateMessageTitle {
            get {
                return ResourceManager.GetString("NewUpdateMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewUpdateMessageVersionText.
        /// </summary>
        public static string NewUpdateMessageVersionText {
            get {
                return ResourceManager.GetString("NewUpdateMessageVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewUpdateMessageCurrentVersionText.
        /// </summary>
        public static string NewUpdateMessageCurrentVersionText {
            get {
                return ResourceManager.GetString("NewUpdateMessageCurrentVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewUpdateMessageUpdateText.
        /// </summary>
        public static string NewUpdateMessageUpdateText {
            get {
                return ResourceManager.GetString("NewUpdateMessageUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateCompletedTitle.
        /// </summary>
        public static string UpdateCompletedTitle {
            get {
                return ResourceManager.GetString("UpdateCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateCompletedTitle.
        /// </summary>
        public static string UpdateCompletedText {
            get {
                return ResourceManager.GetString("UpdateCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBoxRestartButtonText.
        /// </summary>
        public static string MessageBoxRestartButtonText {
            get {
                return ResourceManager.GetString("MessageBoxRestartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpToDateText.
        /// </summary>
        public static string UpToDateText {
            get {
                return ResourceManager.GetString("UpToDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateAvailableText.
        /// </summary>
        public static string UpdateAvailableText {
            get {
                return ResourceManager.GetString("UpdateAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoConnectionText.
        /// </summary>
        public static string NoConnectionText {
            get {
                return ResourceManager.GetString("NoConnectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadingText.
        /// </summary>
        public static string DownloadingText {
            get {
                return ResourceManager.GetString("DownloadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestartRequirementMessageTitle.
        /// </summary>
        public static string RestartRequirementMessageTitle {
            get {
                return ResourceManager.GetString("RestartRequirementMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestartRequirementMessageText.
        /// </summary>
        public static string RestartRequirementMessageText {
            get {
                return ResourceManager.GetString("RestartRequirementMessageText", resourceCulture);
            }
        }
    }
}
